framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        failure_transport: failed

        transports:
            redis:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 3
                    delay: 3000
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # async: '%env(MESSENGER_TRANSPORT_DSN)%'
            failed:
                dsn: '%env(MESSENGER_FAILED_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 3
                    delay: 5000
            sync: 'sync://'

        routing:
            # Route your messages to the transports
             'App\Message\*': redis

when@test:
    framework:
        messenger:
            transports:
                redis: test://
